version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8010"  # Expose backend API
    expose:
      - "8010"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - spelltable-data:/app/data
      - spelltable-logs:/app/logs
      - spelltable-maps:/app/maps
      - spelltable-scenes:/app/scenes
      - spelltable-sounds:/app/sounds
      - spelltable-campaign-images:/app/campaign_images
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8010/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - spelltable-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8010
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8010
    networks:
      - spelltable-network

volumes:
  spelltable-data:
    driver: local
  spelltable-logs:
    driver: local
  spelltable-maps:
    driver: local
  spelltable-scenes:
    driver: local
  spelltable-sounds:
    driver: local
  spelltable-campaign-images:
    driver: local

networks:
  spelltable-network:
    driver: bridge
