version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8010"  # Expose backend API
    expose:
      - "8010"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8010/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - spelltable-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
    ports:
      - "3000:3000"  # Only frontend is accessible from outside
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    environment:
      # Update API URL to use the /api/ path that Apache will proxy
      - NEXT_PUBLIC_API_URL=/api
    networks:
      - spelltable-network

networks:
  spelltable-network:
    driver: bridge
